### ISSUE TITLE
Switch Mojo code using `var` explicitly

### ISSUE THREAD

**Issue by TruongNhanNguyen** [MoSafi2/BlazeSeq#4]
Based on changes in Mojo updates (v24.1 2024-02-29)

> As another step towards [removing `let` declarations](https://github.com/modularml/mojo/blob/main/proposals/remove-let-decls.md) we have removed support for `let` declarations inside the compiler. To ease migration, we parse `let` declarations as a `var` declaration so your code won't break. We emit a warning about this, but please switch your code to using `var` explicitly, because this migration support will be removed in a subsequent update.

_~/MojoFastTrim/MojoFastTrim/fast_parser.mojo_

- Original code snippet:
    ```mojo
    ....
        @always_inline
        fn parse_read(
            self, inout pos: Int, chunk: Tensor[DType.int8]
        ) raises -> RecordCoord:
            let start = pos
            let line1 = get_next_line_index(chunk, pos)
            let line2 = get_next_line_index(chunk, line1 + 1)
            let line3 = get_next_line_index(chunk, line2 + 1)
            let line4 = get_next_line_index(chunk, line3 + 1)
            pos = line4 + 1
            return RecordCoord(start, line1, line2, line3, line4)
    ....
    ```
- Updated code snippet:
  ```mojo
  ....
 
    @always_inline
    fn parse_read(
        self, inout pos: Int, chunk: Tensor[DType.int8]
    ) raises -> RecordCoord:
        var start = pos
        var line1 = get_next_line_index(chunk, pos)
        var line2 = get_next_line_index(chunk, line1 + 1)
        var line3 = get_next_line_index(chunk, line2 + 1)
        var line4 = get_next_line_index(chunk, line3 + 1)
        pos = line4 + 1
        return RecordCoord(start, line1, line2, line3, line4)
  ....
  ```
In this function implementation, we should use `var` instead of `let`, because `let` is being removed. I hope you will update (fix) the code base to make it stay up to date with Mojo latest changes.

**Comment by Moosems** [comment]
Simple find and replace through the codebase? Can I make a PR fixing this?

**Comment by MoSafi2** [comment]
@TruongNhanNguyen @Moosems Thanks guys for having intrest in the matter. 
I didn't change it as MojoFastTrim will recieve a re-write in the next two days. 
Sure, if you would like to make a PR, that more than welcome and appreciated.

**Comment by Moosems** [comment]
How major is the rewrite, if I may?

**Comment by MoSafi2** [comment]
> How major is the rewrite, if I may?

It is a rewrite from the grounds up for the whole backend. Moving the logic of finding new line from the parser module into a buffered reader and line iterator, introducing quality schema, parametric quality and ASCII validation ..etc 
The current version of MojoFastTrim will be retired for historical purposes (but I want to keep it in a functional state) and the new development will be happening in this version. 
If you would like you can follow the repo so you check the new code and hopefully also contribute if you would like to.

**Comment by Moosems** [comment]
Is it the dev branch?

**Comment by MoSafi2** [comment]
> Is it the dev branch?
No, all the code is in another private repo and I will bring all the code here once it's complete (hopefully over the weekend). 
If you are interested, I can also add you to it.

**Comment by Moosems** [comment]
I'd be willing to take a look at it

**Comment by MoSafi2** [comment]
I updated let to var, which should make it work up to 24.1
Although to migrate the old code to 24.2, more substantial changes are needed. 
for example, the `read_bytes()`signature was completly changed to return `List[Int8]` indtead of `Tensor[DType.int8]`
