### ISSUE TITLE
[Feature] Implement buffered writer

### ISSUE THREAD

**Issue by MoSafi2** [MoSafi2/BlazeSeq#5]
Currently, only buffered reader and line iterator is implement allowing only file read and parsing. 
The plan is to allow also output through a buffered writer class. 
Features:
* The writer should support partial input and should flush all contents once reached capacity. 
 * It should accept `Tensor[DType.int8]` as input and converts the buffer content to `String` during writing.
 * can write to memory or file buffer.

**Comment by Moosems** [comment]
Nuts it's taking.... numbers

**Comment by MoSafi2** [comment]
@Moosems Yes, I benchmarked in the beginning both `read()`and `read_bytes()` and reading bytes without string conversion saves around 30% from the IO (the same with python). Also, currently, string operation in Mojo is a bit unoptimized so we have to hand-roll some stuff currently untill Mojo stabilitzes a bit.

**Comment by MoSafi2** [comment]
I think an MRE is harder currently as Mojo IO changed a lot in 24.2

```mojo
from time import now
var handle = open("path/to/file", "r")
var tic = now()
# var x = handle.read()
var x = handle.read_bytes() # Should be 30% faster in mojo 0.6
var toc = now()
print(toc - tic)
```
in Mojo 0.6 using `read_bytes()` was associated with 30% increase in performance. The same trick is also usually used in the python and other languages. The idea is to avoid byte to character decoding step. 

Another reason why it is useful to do the reading in bytes in this problem (FASTQ parsing). 
the format itself uses string encoding of numerical quality value ([Phred scoring](https://en.wikipedia.org/wiki/Phred_quality_score)). so "?" ASCII: 63 is actually encoding the number 30  (63 - 33 (offset))
So, Here is also useful to work with bytes and use `>` and `<` and different mathmatical manipulation for range checking for example. 

For the BufferedWriter, eventually a `byte -> chr` conversion should happen before writing the results to file. It can happen when the buffer is full before flushing the results to the file, or the buffer itself can be a character buffer and request that depositor do the conversion beforehand.

**Comment by Moosems** [comment]
So effectively take ASCII characters as bytes though int8's and once the buffer is filled convert them all at once into chars and write them out?

**Comment by Moosems** [comment]
https://github.com/python/cpython/blob/1c434688866db79082def4f9ef572b85d85908c8/Lib/_py_abc.py#L14
https://github.com/python/cpython/blob/1c434688866db79082def4f9ef572b85d85908c8/Lib/_pyio.py#L312
https://github.com/python/cpython/blob/1c434688866db79082def4f9ef572b85d85908c8/Lib/_pyio.py#L658
https://github.com/python/cpython/blob/1c434688866db79082def4f9ef572b85d85908c8/Lib/_pyio.py#L764
https://github.com/python/cpython/blob/1c434688866db79082def4f9ef572b85d85908c8/Lib/_pyio.py#L1214

**Comment by Moosems** [comment]
Yikes, this is no small task

**Comment by MoSafi2** [comment]
@moosems, you don't have to copy Python's implementation or to make it full featured, as mostly the Stdlib will support the same funtionality sooner or later. 
We can make a simple BufferedWriter which contains:
* Internal container (Tensor or a List) to holds the data
* FileHandle  where to flush the buffer
* a variable where it stores the position within the buffer
We simply need to implement a `store()`function to check to copy the income data, and it checks if the buffer is full, if so it flushes it first.

**Comment by Moosems** [comment]
And a function to flush anything that may remain

**Comment by MoSafi2** [comment]
@Moosems Yes, we also need a publish `flush_buffer()` function.

**Comment by Moosems** [comment]
@MoSafi2 Can we use SIMD/multithreading to reduce conversion time by changing all the int8's at once?

**Comment by Moosems** [comment]
Yeah, `SIMD` [implements](https://docs.modular.com/mojo/stdlib/builtin/simd#:~:text=%2C%20Sized%2C-,Stringable,-Methods%3A) `Stringable`

**Comment by MoSafi2** [comment]
@Moosems I implemented a change in the `FastqRecord()` where if you call `record.__contact_record` it will return a string representation ending in `\n`, so the buffered writer can work directly with text now. It just need to take in a string. Let's see the performance of this case first.
